spring: 
  application:
    name: user-api
server:
  port: ${PORT:8000}
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761/eureka}
  instance:
    hostname: http://localhost:8761
    prefer-ip-address: true