spring: 
  application:
    name: eureka-server
server:
  port: ${PORT:8761}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: ${eureka_url:http://localhost:8761//eureka}
  instance:
    hostname: http://localhost:8761
    prefer-ip-address: true